
package exammanagementsystem;
import java.sql.*;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import projectconnection.ConnectionProj; //here database connection class included

public class AddNewQuestion extends javax.swing.JFrame {
    
    static Connection con = null;
    Statement stmt = null;
    ResultSet rs = null;
    PreparedStatement pst = null;
   
    public AddNewQuestion() {
        initComponents();
        try{
            con = ConnectionProj.getConnection();
            stmt = con.createStatement();
            rs = stmt.executeQuery("select count(id) from question");
            if(rs.first()) //it executed when have 1 value in database 
            {
                int id = rs.getInt(1);
                id  = id+1;     //id number increase by 1
                String st = String.valueOf(id);
                queid_txt.setText(st);
            }
            else
            {
                //not any single id value exit that case this condition executed 
                queid_txt.setText("1");
            }
        }    
        catch(Exception e)
        {
            JFrame jf = new JFrame();
            jf.setAlwaysOnTop(true);
            JOptionPane.showMessageDialog(jf, e);
            
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        adque_lbl = new javax.swing.JLabel();
        close_btn = new javax.swing.JButton();
        jSeparator1 = new javax.swing.JSeparator();
        ans_lbl = new javax.swing.JLabel();
        queid_lbl = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        op1_lbl = new javax.swing.JLabel();
        op2_lbl = new javax.swing.JLabel();
        op3_lbl = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        ans_txt = new javax.swing.JTextField();
        que_txt = new javax.swing.JTextField();
        op1_txt = new javax.swing.JTextField();
        op2_txt = new javax.swing.JTextField();
        queid_txt = new javax.swing.JTextField();
        op3_txt = new javax.swing.JTextField();
        op4_txt = new javax.swing.JTextField();
        clear_btn = new javax.swing.JButton();
        save_btn1 = new javax.swing.JButton();
        bg_lbl = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Add New Question");
        setAlwaysOnTop(true);
        setLocation(new java.awt.Point(0, 170));
        setUndecorated(true);
        setSize(new java.awt.Dimension(0, 0));

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        adque_lbl.setBackground(new java.awt.Color(255, 153, 153));
        adque_lbl.setFont(new java.awt.Font("Algerian", 1, 50)); // NOI18N
        adque_lbl.setForeground(new java.awt.Color(0, 51, 204));
        adque_lbl.setIcon(new javax.swing.ImageIcon(getClass().getResource("/adque.png"))); // NOI18N
        adque_lbl.setText("Add New Questions ");
        jPanel1.add(adque_lbl, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 10, -1, 90));

        close_btn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/exit.png"))); // NOI18N
        close_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                close_btnActionPerformed(evt);
            }
        });
        jPanel1.add(close_btn, new org.netbeans.lib.awtextra.AbsoluteConstraints(1770, 20, 70, 70));
        jPanel1.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 102, 2220, 10));

        ans_lbl.setFont(new java.awt.Font("Tahoma", 1, 25)); // NOI18N
        ans_lbl.setText("  Answer :");
        jPanel1.add(ans_lbl, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 550, 130, 40));

        queid_lbl.setFont(new java.awt.Font("Tahoma", 1, 25)); // NOI18N
        queid_lbl.setText("Question Id");
        jPanel1.add(queid_lbl, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 160, 150, 40));

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 25)); // NOI18N
        jLabel4.setText("Question :");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 250, 130, 40));

        op1_lbl.setFont(new java.awt.Font("Tahoma", 1, 25)); // NOI18N
        op1_lbl.setText("Option 1 :");
        jPanel1.add(op1_lbl, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 310, 130, 40));

        op2_lbl.setFont(new java.awt.Font("Tahoma", 1, 25)); // NOI18N
        op2_lbl.setText("Option 2 :");
        jPanel1.add(op2_lbl, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 370, 130, 40));

        op3_lbl.setFont(new java.awt.Font("Tahoma", 1, 25)); // NOI18N
        op3_lbl.setText("Option 3 :");
        jPanel1.add(op3_lbl, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 430, 130, 40));

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 25)); // NOI18N
        jLabel8.setText("Option 4 :");
        jPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 490, 130, 40));

        ans_txt.setFont(new java.awt.Font("Tahoma", 1, 25)); // NOI18N
        jPanel1.add(ans_txt, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 560, 880, 40));

        que_txt.setFont(new java.awt.Font("Tahoma", 1, 25)); // NOI18N
        jPanel1.add(que_txt, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 260, 880, -1));

        op1_txt.setFont(new java.awt.Font("Tahoma", 1, 25)); // NOI18N
        jPanel1.add(op1_txt, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 320, 880, 40));

        op2_txt.setFont(new java.awt.Font("Tahoma", 1, 25)); // NOI18N
        jPanel1.add(op2_txt, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 380, 880, 40));

        queid_txt.setFont(new java.awt.Font("Tahoma", 1, 25)); // NOI18N
        queid_txt.setForeground(new java.awt.Color(255, 51, 51));
        queid_txt.setText("00");
        jPanel1.add(queid_txt, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 172, -1, 40));

        op3_txt.setFont(new java.awt.Font("Tahoma", 1, 25)); // NOI18N
        jPanel1.add(op3_txt, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 440, 880, 40));

        op4_txt.setFont(new java.awt.Font("Tahoma", 1, 25)); // NOI18N
        jPanel1.add(op4_txt, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 500, 880, 40));

        clear_btn.setBackground(new java.awt.Color(51, 102, 255));
        clear_btn.setFont(new java.awt.Font("Tahoma", 1, 30)); // NOI18N
        clear_btn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/clear.png"))); // NOI18N
        clear_btn.setText("Clear");
        clear_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                clear_btnActionPerformed(evt);
            }
        });
        jPanel1.add(clear_btn, new org.netbeans.lib.awtextra.AbsoluteConstraints(1000, 720, 190, 90));

        save_btn1.setBackground(new java.awt.Color(51, 102, 255));
        save_btn1.setFont(new java.awt.Font("Tahoma", 1, 30)); // NOI18N
        save_btn1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/save.png"))); // NOI18N
        save_btn1.setText("Save\n");
        save_btn1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                save_btn1ActionPerformed(evt);
            }
        });
        jPanel1.add(save_btn1, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 720, 190, 90));

        bg_lbl.setIcon(new javax.swing.ImageIcon(getClass().getResource("/add quesbg.jpg"))); // NOI18N
        jPanel1.add(bg_lbl, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 2160, 1070));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 2223, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void close_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_close_btnActionPerformed
        // TDO add your handling code here:
        AdminHome.open=0;
        setVisible(false);
    }//GEN-LAST:event_close_btnActionPerformed

    private void save_btn1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_save_btn1ActionPerformed
        // TODO add your handling code here:
        String id = queid_txt.getText();
        String name = que_txt.getText();
        String op1 = op1_txt.getText();
        String op2 = op2_txt.getText();
        String op3 = op3_txt.getText();
        String op4 = op4_txt.getText();
        String answer = ans_txt.getText();
        
        
        try
        {  
            con = ConnectionProj.getConnection();
            pst = con.prepareStatement("insert into question values(?,?,?,?,?,?,?)"); //database query using preparaStatement
        
            pst.setString(1, id);
            pst.setString(2, name);
            pst.setString(3, op1);
            pst.setString(4, op2);
            pst.setString(5, op3);
            pst.setString(6, op4);
            pst.setString(7, answer);
            pst.executeUpdate();
            
            JFrame jf = new JFrame();
            jf.setAlwaysOnTop(true);
            JOptionPane.showMessageDialog(jf, "Successfully Updated");
            setVisible(false);
            
            new AddNewQuestion().setVisible(true);
            
            
        }
        catch(Exception e)
        {
            JFrame jf = new JFrame();
            jf.setAlwaysOnTop(true);
            JOptionPane.showMessageDialog(jf, e);
        }
    }//GEN-LAST:event_save_btn1ActionPerformed

    private void clear_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_clear_btnActionPerformed
        // TODO add your handling code here:
        queid_txt.setText("");
        que_txt.setText("");
        op1_txt.setText("");
        op2_txt.setText("");
        op3_txt.setText("");
        op4_txt.setText("");
        ans_txt.setText(""); 
       
    }//GEN-LAST:event_clear_btnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AddNewQuestion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AddNewQuestion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AddNewQuestion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AddNewQuestion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AddNewQuestion().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel adque_lbl;
    private javax.swing.JLabel ans_lbl;
    private javax.swing.JTextField ans_txt;
    private javax.swing.JLabel bg_lbl;
    private javax.swing.JButton clear_btn;
    private javax.swing.JButton close_btn;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JLabel op1_lbl;
    private javax.swing.JTextField op1_txt;
    private javax.swing.JLabel op2_lbl;
    private javax.swing.JTextField op2_txt;
    private javax.swing.JLabel op3_lbl;
    private javax.swing.JTextField op3_txt;
    private javax.swing.JTextField op4_txt;
    private javax.swing.JTextField que_txt;
    private javax.swing.JLabel queid_lbl;
    private javax.swing.JTextField queid_txt;
    private javax.swing.JButton save_btn1;
    // End of variables declaration//GEN-END:variables
}
